# -*- coding: utf-8 -*-
"""01[day5].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pgemQsxDVR36w-nSZGMgjoz9BHPU2H3p
"""

name1 = input("Enter first name: ").lower().replace(" ", "")
name2 = input("Enter second name: ").lower().replace(" ", "")

list1 = list(name1)
list2 = list(name2)

# Remove common letters
for i in list1[:]:
    if i in list2:
        list1.remove(i)
        list2.remove(i)

# Count remaining letters
count = len(list1) + len(list2)

# FLAMES list
flames = ["F", "L", "A", "M", "E", "S"]

# Circular elimination
while len(flames) > 1:
    index = (count % len(flames)) - 1

    if index >= 0:
        right = flames[index+1:]
        left = flames[:index]
        flames = right + left
    else:
        flames = flames[:-1]

# Final result
result = flames[0]

if result == "F":
    print("Friends")
elif result == "L":
    print("Love")
elif result == "A":
    print("Affection")
elif result == "M":
    print("Marriage")
elif result == "E":
    print("Enemy")
else:
    print("Sibling")

a=input("enter a boy name: ")
b=input("enter a girl name: ")
a1=list(a)
b1=list(b)
for i in range(len(a1)):
    for j in range(len(b1)):
        if a1[i]==b1[j]:
            a1[i]='2'
            b1[j]='2'
print(a1)
print(b1)
cnt=0
for i in a1:
    if i!='2':
        cnt=cnt+1
for i in b1:
    if i!='2':
        cnt=cnt+1
print(cnt)
index=0
res=list("FLAMES")
for i in range(5):
    index=(index+(cnt-1))%len(res)
    res.pop(index)
print(res[0])

nums = list(map(int, input().split()))
res = []
res.append(nums[0])

for i in range(1, len(nums)):
    d = res[-1] + nums[i]
    res.append(d)
print(res)

a = [[" " for i in range(11)] for i in range(11)]

for i in range(11):
    for j in range(11):
        if j == 0 or j == 10:
            a[i][j] = "*"

        if i == j and i < 6:
            a[i][j] = "*"

        if i + j == 10 and i < 6:
            a[i][j] = "*"

for row in a:
    print(" ".join(row))

