# -*- coding: utf-8 -*-
"""5[day9].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcaQW7LkfZyJz7kWnFpHzSPBJn_WgQAU

prime factorization
100 50 25  5 1
2 2 5 5
75
3 5 5
"""

def vaishnavi(a):
    if a==1:
        return
    i=2
    while(a%i!=0):
        i=i+1
    print(i)
    vaishnavi(a/i)
a=int(input("enter any number: "))
vaishnavi(a)

def vaishnavi(a):
    while a > 1:
        i = 2
        while a % i != 0:
            i += 1
        print(i)
        a = a // i
a = int(input("enter any number: "))
vaishnavi(a)

class rect:
    def __init__(self,a,b):#constrctor
        self.area=a*b
    def display(self):
        print("area:",self.area)
r=rect(20,30)
r.display()

class circle:
    def __init__ (self):
        x=int(input("radius"))
        self.r=x
    def display(self):
            print("area is",3.14*self.r**2)
a=int(input("enter no of circle"))
l=[]
for i in range(a):
    c=circle()
    l.append(c)
    c.display()
    print("---------------")

"""* data structues: aim:better tc&sc -- need for  better time complexity: performance=TS
* space complexity=(diectly proportional)commercial
* 2structures: linear & non linear
* linear: arranged in sequence,one layer,ex:array,linked list,stack ,queue
* non-linear: stored in multi layer,hierarchial manner,ex: tree,graph
* linked-list:[joined]elements stored in series of nodes,node[data stored] [head]1st node.
* difference btw ll and others:concerned with address
*  non-contigious memory allocations[10,28,81] no indexing  ,array-- indexing possible,contigious [10,12,13](similarity:both are linear)
* java\\python: j-secured lang,portable lang,we cant find address
* 4types: single linked list/doubly linked list/circular linked list/circular double linked list.
* SINGLE: node hs 2 parts: data/address,unidirectional
* DOUBLE: bidirectional,head prev next
* CIRCULAR: no null in any node last node connected to 1st
* DOUBLE circular: cobination of both double and circular

"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class linkedlist:
    def __init__(self):
        self.head = None

    def insert(self, data):
        newnode = Node(data)
        if self.head is None:   # fixed syntax
            self.head = newnode
        else:
            temp = self.head
            while temp.next:
                temp = temp.next
            temp.next = newnode

    def display(self):
        temp = self.head
        while temp:
            print(temp.data, end="->")
            temp = temp.next   # fixed indentation


l = linkedlist()
l.insert(100)
l.insert(200)
l.insert(300)
l.insert(400)
l.display()